
FROM node:16-alpine


RUN addgroup app && adduser -S -G app app
RUN mkdir /app && chown app:app /app
USER app

WORKDIR '/app'

COPY --chown=app:app package.json .

RUN npm install

COPY --chown=app:app . .

CMD ["npm","run","start"]

